export { default as useCreate } from './useCreate'
export { default as useUpdate } from './useUpdate'
export { default as useList } from './useList'
export { default as useDetail } from './useDetail'
export { default as useRemove } from './useRemove'
